// Generated by CoffeeScript 1.6.3
/*

    corporation || ~>
*/

var deferred, nodule,
  __slice = [].slice;

deferred = require('decor').deferred;

nodule = require('vertex').nodule;

nodule.exports = function() {
  var pending;
  pending = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return deferred(function(action, opts, callback) {});
};

nodule.exports.meta = function() {};
